import os
import functools

SCRIPT_DIR: str = os.path.dirname(os.path.realpath(__file__))


def to_snake_case(name: str) -> str:
    return functools.reduce(lambda x, y: x + ('_' if y.isupper() else '') + y, name).lower()


def process(module_name, file):
    # get current script directory
    src_index = SCRIPT_DIR.rfind("src")
    assert src_index != -1, "src not found in the path"
    header_path = os.path.join(SCRIPT_DIR[:src_index], "include",
                               "luisa", "xir", "instructions",
                               f"{to_snake_case(module_name)}.h")
    with open(header_path, "r") as f:
        lines = [x for line in f.readlines() if (x := line.strip()) and not x.startswith("//")]
        try:
            enum_index = lines.index(f"enum struct {module_name}Op {{") + 1
        except ValueError:
            enum_index = lines.index(f"enum class {module_name}Op {{") + 1
        lines = lines[enum_index:]
        enum_end = lines.index("};")
        ops = [line.split(",")[0].strip() for line in lines[:enum_end]]
    file.write(f"""luisa::string_view to_string({module_name}Op op) noexcept {{
    using namespace std::string_view_literals;
    switch (op) {{
""")
    file.writelines([f"        case {module_name}Op::{op}: return \"{op.lower()}\"sv;\n" for op in ops])
    file.write(f"""    }}
    LUISA_ERROR_WITH_LOCATION("Unknown {to_snake_case(module_name)} operation (code = {{}}).",
                          static_cast<uint32_t>(op));
}}

{module_name}Op {to_snake_case(module_name)}_op_from_string(luisa::string_view name) noexcept {{
    using namespace std::string_view_literals;
    static const luisa::unordered_map<luisa::string_view, {module_name}Op> m{{
""")
    file.writelines([f"        {{\"{op.lower()}\"sv, {module_name}Op::{op}}},\n" for op in ops])
    file.write(f"""    }};
    auto iter = m.find(name);
    LUISA_ASSERT(iter != m.end(), "Unknown {to_snake_case(module_name)} operation: {{}}.", name);
    return iter->second;
}}

""")


if __name__ == "__main__":
    module_names = ["Arithmetic", "Atomic", "Cast", "Intrinsic", "ThreadGroup"]
    with open(f"{SCRIPT_DIR}/op_name_map.cpp", "w") as file:
        file.write("// This file is generated by update_intrinsic_name_map.py\n")
        file.write("// Do not edit it manually.\n\n")
        file.write("#include <luisa/core/logging.h>\n")
        file.write("#include <luisa/core/stl/unordered_map.h>\n")
        file.write("\n")
        for module_name in module_names:
            file.write(f"#include <luisa/xir/instructions/{to_snake_case(module_name)}.h>\n")
        file.write("\n")
        file.write("namespace luisa::compute::xir {\n\n")
        for module_name in module_names:
            process(module_name, file)
        file.write("}\n")
